services:
  mongo:
    image: mongo
    container_name: "mongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: fox
      POSTGRES_PASSWORD: raymond
      POSTGRES_DB: my_database
    volumes:
      - './dockervolume/postgresdb:/data/db'
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge